services:
  web:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - netowo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: asd
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes: 
      - ./db:/data/db
    networks:
      - netowo

  mongoexp:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://asd:root@mongo:27017/admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    networks:
      - netowo

networks:
  netowo:
    driver: bridge
  